name: tus_client
description: A library for uploading files using the tus protocol to any remote server supporting it.
repository: https://github.com/rodrigost23/tus-dart-client
version: 0.0.1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
  coverage: ">=0.13.0 <0.14.0"
